site_name: MosPy Docs
plugins:
  - search
  - mkdocstrings:
      watch:
        - src/mospy

nav:
  - Overview: "index.md"
  - "account.md"
  - "transaction.md"
  - Clients:
      - Overview: 'clients\index.md'
      - HTTPClient: 'clients\httpclient.md'
      - GRPCClient: 'clients\grpcclient.md'
  - 'examples.md'
theme:
  name: "material"
